site_name: ICR SD&CC
nav:
  - Home: 'index.md'
  - About: 'about.md'
  #- Events: 'events.md'
  #- Past events: 'p-events.md'


theme:
  name: material  
  logo: assets/icr_sd&cc.jpg  
  favicon: assets/icr_sd&cc.jpg  
  palette:
    primary: pink  
    accent: deep orange  
